name: newspaper-headline-summarizer
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.9
  - pip
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  # - pytorch-cuda=11.8  # Comment this line if you don't have CUDA
  - transformers>=4.30.0
  - datasets>=2.12.0
  - accelerate>=0.20.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - tqdm>=4.65.0
  - sentencepiece>=0.1.99
  - jupyter>=1.0.0
  - ipywidgets>=8.0.0
  - pip:
    - langchain>=0.1.0
    - langchain-community>=0.0.10
